### PR TITLE
Update to Zig 0.13.0

### PR DESCRIPTION
**Pull request by photex**
- Update dependencies and build scripts to account for Build api changes
- Shader update with latest sokol-shdc - glsl330 was apparently replaced by glsl430?
- Update zig-gamedev libraries in 3rdparty

### CODE REVIEW

**Comment by photex** [comment]
I hadn't checked the web build initially, but have now corrected things so that web builds do indeed run again.

**Comment by Interrupt** [comment]
Thanks! I was just looking at doing this. I'll test this out and hopefully get it merged in soon.

**Comment by photex** [comment]
Awesome! I realize you probably aren’t on the lookout for contributors dropping stuff like this but perhaps selfishly I just did it to understand the differences myself and figured I should share the results.

**Comment by Interrupt** [comment]
No way, I love PRs like these! I would much rather be adding functionality instead of mucking with build systems 😄 

Checked out those changes and it looks like audio isn't working for Emscripten builds yet, opened a PR for your PR: https://github.com/photex/delve-framework/pull/1

**Pull request merged**
