### PR TITLE
update to zig 0.14.0-dev.296+bd7b2cc4b

### PR DESCRIPTION
**Pull request by Jack-Ji**

### CODE REVIEW

**Comment by Interrupt** [comment]
Thanks for this! I think we'll want to merge this into a new `0.14-dev` branch to keep `main` on the latest stable release.

**Comment by Jack-Ji** [comment]
No problem! Just one thing, several examples can't compile successfully (skinned_animation/stresstest etc), it seems vertex layout isn't compatible with shader, and updating sokol-zig to latest doesn't fix it. Since I'm new to sokol-zig, maybe you can take a look into the problem.

**Comment by Interrupt** [comment]
Just merged this work into https://github.com/Interrupt/delve-framework/tree/0.14.0-dev - had to make one small change to the cimgui dependency hash to get it to build.

All of the examples seem to build and run for me, what platform are you running on? It could be a difference between shader backends.

**Comment by Jack-Ji** [comment]
You are right. I'm using Debian Linux, and zig-0.13.0 doesn't compile some of  main branch's examples either. 

As for cimgui's dependency hash, zig reported inconsistent hash on my machine, hence the modification. It seems different version of zig compiler give different hash for some reason.

Since its merged already, I'm closing the PR.

**Pull request closed without merging**
